/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.miapp.triage.gui;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fran
 */
public class Historialclinica extends javax.swing.JFrame {

    /**
     * Creates new form Historialclinica
     */
    
    public Historialclinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Fecha", "Hora", "Lugar", "Medico", "Diagnostico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultaGUI consul = new ConsultaGUI();
        consul.setVisible(true);
        consul.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    
    public void cargarDatosPaciente(String dniPaciente) {
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("Paciente");
    modeloTabla.addColumn("Fecha");
    modeloTabla.addColumn("Hora");
    modeloTabla.addColumn("Lugar");
    modeloTabla.addColumn("Médico");
    modeloTabla.addColumn("Diagnóstico");

    try {
        BufferedReader brConsulta = new BufferedReader(new FileReader("src\\main\\java\\com\\miapp\\triage\\csv\\Consultas.csv"));
        BufferedReader brPacientes = new BufferedReader(new FileReader("src\\main\\java\\com\\miapp\\triage\\csv\\pacientes.csv"));
        String lineaConsulta;
        String lineaPacientes;

        // Crear un mapa para almacenar el nombre de los pacientes
        Map<String, String> nombresPacientes = new HashMap<>();

        while ((lineaPacientes = brPacientes.readLine()) != null) {
            String[] datosPacientes = lineaPacientes.split(";");
            if (datosPacientes.length >= 10) {
                String dni = datosPacientes[5];
                String nombre = datosPacientes[1];
                String apellido = datosPacientes[2];
                String nombreCompleto = nombre + " " + apellido;
                nombresPacientes.put(dni, nombreCompleto);
            }
        }

        while ((lineaConsulta = brConsulta.readLine()) != null) {
            String[] datosConsulta = lineaConsulta.split(";");
            if (datosConsulta.length >= 8) {
                String dni = datosConsulta[0];
                if (dni.equals(dniPaciente)) {
                    String Fecha = datosConsulta[1];
                    String Hora = datosConsulta[2];
                    String Lugar = datosConsulta[3];
                    String Medico = datosConsulta[7];
                    String Diagnostico = datosConsulta[5];
                    
                    // Obtén el nombre del paciente desde el mapa
                    String nombrePaciente = nombresPacientes.get(dniPaciente);

                    // Agrega una fila al modelo de datos
                    modeloTabla.addRow(new Object[] {nombrePaciente, Fecha, Hora, Lugar, Medico, Diagnostico});
                }
            }
        }

        brConsulta.close();
        brPacientes.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    // Asigna el modelo de datos a la tabla
    jTable1.setModel(modeloTabla);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historialclinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historialclinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historialclinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historialclinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historialclinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
